//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsBasvurusu.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class FormTab
    {
        public int userId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string birthDay { get; set; }
        public string gender { get; set; }
        public string endYear { get; set; }
        public string grade { get; set; }
        public string phoneNumber { get; set; }
        public string school { get; set; }
        public string degree { get; set; }
        public string message { get; set; }
        public string adminMail { get; set; }
        public string password { get; set; }
        public string subject { get; set; } 
        public HttpPostedFileBase attachment { get; set; }
        static public bool addMail(string firstName,
                                    string lastName,
                                    string birthday,
                                    string gender,
                                    string phoneNumber,
                                    string school,
                                    string endYear,
                                    string  grade,
                                    string password,
                                    string subject,
                                    string message)
        {
            using (IsBasvurusuEntities4 ent = new IsBasvurusuEntities4())
            {

                FormTab f = new FormTab();
                f.firstName = firstName;
                f.lastName = lastName;
                f.birthDay = birthday;
                f.gender = gender;
                f.phoneNumber = phoneNumber;
                f.school = school;
                f.endYear = endYear;
                f.grade = grade;
                f.password = password;
                f.subject = subject;
                f.message = message;

               ent.Set<Models.FormTab>().Add(f);
                ent.SaveChanges();

                return true;
            }

        }
        
    }
}
